[spdx]
ignore-licenses = [
    # Apache-2.0 is often misclassified as Pixar, which is a significantly more rare
    # https://github.com/jpeddicord/askalono/issues/94
    "Pixar"
]

[clarify."sigs.k8s.io/yaml"]
# The package's files are a mix of MIT with contributions attributed to "The Go
# Authors" licensed as BSD-3-Clause.
expression = "MIT AND BSD-3-Clause"
license-files = [
    { path = "LICENSE", hash = 0xcdf3ae00 },
]

[clarify.crossbeam-channel]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xbc436f08 },
    { path = "LICENSE-THIRD-PARTY", hash =0x847bf39 },
]

[clarify.regex]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xb755395b },
]
skip-files = [
    "src/testdata/LICENSE", # we aren't using the test data
]

[[clarify.regex-automata]]
version = "^0.1"
expression = "Unlicense OR MIT"
license-files = [
    { path = "LICENSE-MIT", hash = 0x616d8a83 },
    { path = "UNLICENSE", hash = 0x87b84020 },
]
skip-files = [
    # these licenses apply to the test data, which we don't distribute,
    "data/tests/fowler/LICENSE",
    "data/fowler-tests/LICENSE",
    # this file describes what licenses apply to the sources, and when they apply
    "COPYING"
]

[[clarify.regex-automata]]
version = "^0.3"
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-MIT", hash = 0xb755395b },
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
]

[clarify.regex-syntax]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xb755395b },
    { path = "src/unicode_tables/LICENSE-UNICODE", hash = 0xa7f28b93 },
]

[clarify.typenum]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x91d5a0a7 },
    { path = "LICENSE-MIT", hash = 0xb9f15462 },
    { path = "LICENSE", hash = 0xa4618a29 },
]

[clarify.zstd-sys]
# The zstd-sys crate's license is listed as MIT or Apache2
#
# zstd-sys compiles zstd as a static library.
#
# zstd's README file states:
# "Zstandard is dual-licensed under BSD and GPLv2."
expression = "(MIT OR Apache-2.0) AND (BSD-3-Clause OR GPL-2.0)"
license-files = [
    { path = "LICENSE", hash = 0x742401ae },
    { path = "LICENSE.Apache-2.0", hash = 0x7b466be4 },
    { path = "LICENSE.BSD-3-Clause", hash = 0xc9f5c4f6},
    { path = "LICENSE.Mit", hash = 0xa237d234 },
    { path = "zstd/COPYING", hash = 0x96841aa4 },
    { path = "zstd/LICENSE", hash =  0x3bfe1fb1 },
]
skip-files = [
    # Files under zstd/build are for IDE integrations, and are unused.
    "zstd/build/LICENSE"
]

[clarify.zstd-safe]
# The zstd-safe crate's license is listed as MIT or Apache2
#
# zstd-safe compiles zstd as a thin wrapper for zstd.
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0x742401ae },
    { path = "LICENSE.Mit", hash = 0xa237d234 },
    { path = "LICENSE.Apache-2.0", hash = 0x7b466be4 },
]

[clarify.minimal-lexical]
expression = "(MIT OR Apache-2.0) AND BSD-3-Clause"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x4fccb6b7 },
    { path = "LICENSE-MIT", hash = 0x386ca1bc },
    { path = "LICENSE.md", hash = 0xfe66d806 },
]

[clarify.rustls-webpki]
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]
